apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: holbora-com-tls
spec:
  secretName: holbora-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: holbora.com
  dnsNames:
    - holbora.com
    - www.holbora.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - holbora.com
          - www.holbora.com